db_filename: [test_generated_db.json, logic_generated_db.json, scan_generated_db.json]
Layer:
  order: [M1, M2, M3, M4, M5]
  orientation: ['|', '-', '|', '-', '|']
  viamap:
    - [via_M1_M2_0, via_M1_M2_1]
    - [via_M2_M3_0, via_M2_M3_1]
    - [via_M3_M4_0, via_M3_M4_1]
    - [via_M4_M5_0, via_M4_M5_1]
Via:
  via_M1_M2_0:
    map: [M1, M2]
    extension: [10, 10]
  via_M1_M2_1:
    map: [M1, M2]
    extension: [10, 20]
  via_M2_M3_0:
    map: [M2, M3]
    extension: [10, 10]
  via_M2_M3_1:
    map: [M2, M3]
    extension: [10, 20]
  via_M3_M4_0:
    map: [M3, M4]
    extension: [10, 10]
  via_M3_M4_1:
    map: [M3, M4]
    extension: [10, 20]
  via_M4_M5_0:
    map: [M4, M5]
    extension: [10, 10]
  via_M4_M5_1:
    map: [M4, M5]
    extension: [10, 20]

Equivalent_net_sets:
  "VDD:":
    - "VDD:"
    - "VDD"
    - "vdd"
    - "vdd:"
  "VSS:":
    - "VSS:"
    - "VSS"
    - "vss"
    - "vss:"
    - "gnd"
  
